version: '3.3'
services:
  siraat-backend:
    container_name: siraat-backend
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
 data: {}